"use client"

import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import { BellPlus, CalendarClock, CheckSquare, CircleAlert, ListTodo, Loader2, Trash2 } from "lucide-react"
import { toast } from "sonner"
import {
  reminderService,
  CreatedReminderLink,
  ReminderDraft,
  ReminderList,
  ReminderProviderAccount,
  ReminderSettingsState,
} from "@/services/reminderService"

interface ReminderDraftReviewProps {
  meetingId: string
  hasSummary: boolean
}

type EditableDraft = ReminderDraft & {
  selected: boolean
  dirty?: boolean
}

function friendlyError(error: unknown): string {
  const message = error instanceof Error ? error.message : typeof error === "string" ? error : ""
  const lower = message.toLowerCase()
  if (lower.includes("desktop app")) return "Apple Reminders is available in the desktop app."
  if (lower.includes("permission")) return "Apple Reminders permission is needed before suggestions can be prepared."
  if (lower.includes("summary")) return "Generate a meeting summary before creating reminder suggestions."
  if (lower.includes("title is required")) return "Add a reminder title before saving."
  if (lower.includes("priority")) return "Choose a valid reminder priority."
  if (lower.includes("not found")) return "This reminder suggestion is no longer available."
  return "Reminder suggestions could not be loaded."
}

function categoryLabel(category: string): string {
  return category
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ")
}

function priorityLabel(priority?: number | null): string {
  if (!priority) return "None"
  if (priority <= 3) return "High"
  if (priority <= 6) return "Medium"
  return "Low"
}

function toDateTimeInput(value?: string | null): string {
  if (!value) return ""
  const date = new Date(value)
  if (!Number.isFinite(date.getTime())) return ""
  const offsetMs = date.getTimezoneOffset() * 60_000
  return new Date(date.getTime() - offsetMs).toISOString().slice(0, 16)
}

function fromDateTimeInput(value: string): string | null {
  if (!value) return null
  const date = new Date(value)
  return Number.isFinite(date.getTime()) ? date.toISOString() : null
}

function formatCompactDate(value?: string | null): string {
  if (!value) return "No due date"
  const date = new Date(value)
  if (!Number.isFinite(date.getTime())) return "No due date"
  return new Intl.DateTimeFormat(undefined, {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(date)
}

function statusPillClass(status: string): string {
  if (status === "completed") return "bg-emerald-100 text-emerald-800"
  if (status === "open") return "bg-blue-100 text-blue-800"
  if (status === "missing") return "bg-amber-100 text-amber-800"
  if (status === "unavailable") return "bg-slate-100 text-slate-600"
  return "bg-white/80 text-emerald-800"
}

function isConnected(account?: ReminderProviderAccount): boolean {
  return account?.status === "connected"
}

export function ReminderDraftReview({ meetingId, hasSummary }: ReminderDraftReviewProps) {
  const [settings, setSettings] = useState<ReminderSettingsState | null>(null)
  const [drafts, setDrafts] = useState<EditableDraft[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)
  const [savingDraftId, setSavingDraftId] = useState<string | null>(null)
  const [isCreating, setIsCreating] = useState(false)
  const [message, setMessage] = useState<string | null>(null)
  const [createdLinks, setCreatedLinks] = useState<CreatedReminderLink[]>([])
  const autoGeneratedMeetingRef = useRef<string | null>(null)

  const appleAccount = useMemo(
    () => settings?.accounts.find((account) => account.provider === "apple_reminders"),
    [settings],
  )
  const appleLists = useMemo(
    () => settings?.lists.filter((list) => list.providerAccountId === appleAccount?.id && list.selected) ?? [],
    [appleAccount?.id, settings],
  )
  const defaultList = appleLists.find((list) => list.isDefault) ?? appleLists[0]
  const selectedCount = drafts.filter((draft) => draft.selected).length

  const mergeDrafts = useCallback((nextDrafts: ReminderDraft[]) => {
    setDrafts((current) => {
      const currentById = new Map(current.map((draft) => [draft.id, draft]))
      return nextDrafts.map((draft) => {
        const existing = currentById.get(draft.id)
        if (existing?.dirty) {
          return {
            ...draft,
            title: existing.title,
            notes: existing.notes,
            dueAt: existing.dueAt,
            priority: existing.priority,
            listId: existing.listId,
            selected: existing.selected,
            dirty: true,
          }
        }
        return {
          ...draft,
          selected: existing?.selected ?? draft.confidence >= 0.5,
          dirty: false,
        }
      })
    })
  }, [])

  const refresh = useCallback(async () => {
    if (!hasSummary) {
      setDrafts([])
      return
    }

    setIsLoading(true)
    setMessage(null)
    try {
      const [nextSettings, nextDrafts, nextCreatedLinks] = await Promise.all([
        reminderService.getSettings(),
        reminderService.listDrafts(meetingId, false),
        reminderService.listCreated(meetingId),
      ])
      setSettings(nextSettings)
      setCreatedLinks(nextCreatedLinks)
      mergeDrafts(nextDrafts)
    } catch (error) {
      setMessage(friendlyError(error))
    } finally {
      setIsLoading(false)
    }
  }, [hasSummary, meetingId, mergeDrafts])

  useEffect(() => {
    void refresh()
  }, [refresh])

  useEffect(() => {
    if (!hasSummary || !isConnected(appleAccount) || drafts.length > 0 || isLoading || autoGeneratedMeetingRef.current === meetingId) {
      return
    }

    autoGeneratedMeetingRef.current = meetingId
    const generate = async () => {
      setIsGenerating(true)
      setMessage(null)
      try {
        const result = await reminderService.generateDrafts({ meetingId })
        mergeDrafts(result.drafts)
        if (result.drafts.length === 0) {
          setMessage("No clear follow-up reminders were found in this summary.")
        } else if (result.hiddenLowConfidenceCount > 0) {
          setMessage(`${result.hiddenLowConfidenceCount} low-confidence suggestion${result.hiddenLowConfidenceCount === 1 ? "" : "s"} hidden.`)
        }
      } catch (error) {
        setMessage(friendlyError(error))
      } finally {
        setIsGenerating(false)
      }
    }

    void generate()
  }, [appleAccount, drafts.length, hasSummary, isLoading, meetingId, mergeDrafts])

  const updateDraft = (draftId: string, patch: Partial<EditableDraft>) => {
    setDrafts((current) => current.map((draft) => (
      // Selection is transient review state; field edits need an explicit save.
      draft.id === draftId ? { ...draft, ...patch, dirty: patch.selected === undefined ? true : draft.dirty } : draft
    )))
  }

  const saveDraft = async (draft: EditableDraft, showToast = true): Promise<boolean> => {
    setSavingDraftId(draft.id)
    setMessage(null)
    try {
      const updated = await reminderService.updateDraft({
        draftId: draft.id,
        title: draft.title,
        notes: draft.notes ?? null,
        dueAt: draft.dueAt ?? null,
        priority: draft.priority ?? null,
        listId: draft.listId ?? defaultList?.id ?? null,
      })
      setDrafts((current) => current.map((item) => (
        item.id === draft.id ? { ...updated, selected: item.selected, dirty: false } : item
      )))
      if (showToast) toast.success("Reminder draft saved")
      return true
    } catch (error) {
      setMessage(friendlyError(error))
      return false
    } finally {
      setSavingDraftId(null)
    }
  }

  const dismissDraft = async (draftId: string) => {
    setSavingDraftId(draftId)
    setMessage(null)
    try {
      await reminderService.dismissDraft(draftId)
      setDrafts((current) => current.filter((draft) => draft.id !== draftId))
      toast.success("Reminder suggestion dismissed")
    } catch (error) {
      setMessage(friendlyError(error))
    } finally {
      setSavingDraftId(null)
    }
  }

  const createSelectedReminders = async () => {
    const selectedDrafts = drafts.filter((draft) => draft.selected)
    if (selectedDrafts.length === 0) {
      setMessage("Select at least one reminder suggestion.")
      return
    }

    setIsCreating(true)
    setMessage(null)
    try {
      for (const draft of selectedDrafts.filter((draft) => draft.dirty)) {
        const saved = await saveDraft(draft, false)
        if (!saved) {
          setIsCreating(false)
          return
        }
      }

      const result = await reminderService.createSelected({
        meetingId,
        draftIds: selectedDrafts.map((draft) => draft.id),
      })
      setCreatedLinks(await reminderService.listCreated(meetingId))
      const completedIds = new Set([
        ...result.created.map((link) => link.draftId).filter(Boolean),
        ...result.skipped.map((link) => link.draftId).filter(Boolean),
      ])
      const skippedDedupeKeys = new Set(result.skipped.map((link) => link.dedupeKey))
      setDrafts((current) => current.filter((draft) => !completedIds.has(draft.id) && !skippedDedupeKeys.has(draft.dedupeKey)))

      if (result.failed.length > 0) {
        setMessage(`${result.failed.length} reminder${result.failed.length === 1 ? "" : "s"} could not be created. ${result.created.length} created.`)
      } else if (result.skipped.length > 0 && result.created.length === 0) {
        setMessage("Selected reminders were already created for this meeting.")
      } else {
        toast.success(`${result.created.length} reminder${result.created.length === 1 ? "" : "s"} created`)
      }
    } catch (error) {
      setMessage(friendlyError(error))
    } finally {
      setIsCreating(false)
    }
  }

  if (!hasSummary) return null

  if (isLoading) {
    return (
      <div className="mx-6 mb-6 rounded-lg border border-slate-200 bg-white p-4 text-sm text-slate-600">
        <div className="flex items-center gap-2">
          <Loader2 className="h-4 w-4 animate-spin" />
          Loading reminder suggestions...
        </div>
      </div>
    )
  }

  if (!isConnected(appleAccount)) {
    return (
      <div className="mx-6 mb-6 rounded-lg border border-dashed border-slate-300 bg-slate-50 p-5">
        <div className="flex items-start gap-3">
          <div className="rounded-md bg-white p-2 text-slate-600">
            <ListTodo className="h-5 w-5" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-slate-950">Create Apple Reminders from follow-ups</h3>
            <p className="mt-1 text-sm text-slate-600">
              Connect Apple Reminders in settings to review editable follow-up suggestions for this meeting.
            </p>
            {appleAccount?.lastError && (
              <p className="mt-3 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900">
                {appleAccount.lastError}
              </p>
            )}
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="mx-6 mb-6 rounded-lg border border-slate-200 bg-white shadow-sm">
      <div className="flex flex-col gap-3 border-b border-slate-200 p-4 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex items-start gap-3">
          <div className="rounded-md bg-emerald-50 p-2 text-emerald-700">
            <BellPlus className="h-5 w-5" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-slate-950">Create reminders</h3>
            <p className="mt-1 text-sm text-slate-600">
              Review meeting follow-ups before anything is written to Apple Reminders.
            </p>
          </div>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            type="button"
            className="inline-flex items-center gap-2 rounded-md border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"
            onClick={refresh}
            disabled={isGenerating || isCreating || savingDraftId !== null}
          >
            {isGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : <CalendarClock className="h-4 w-4" />}
            Refresh
          </button>
          <button
            type="button"
            className="inline-flex items-center gap-2 rounded-md bg-emerald-600 px-3 py-2 text-sm font-medium text-white hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-60"
            disabled={selectedCount === 0 || isGenerating || isCreating || savingDraftId !== null}
            onClick={createSelectedReminders}
          >
            {isCreating ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckSquare className="h-4 w-4" />}
            Create selected ({selectedCount})
          </button>
        </div>
      </div>

      {message && (
        <div className="mx-4 mt-4 flex items-start gap-2 rounded-md border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700">
          <CircleAlert className="mt-0.5 h-4 w-4 flex-shrink-0" />
          <span>{message}</span>
        </div>
      )}

      {createdLinks.length > 0 && (
        <div className="mx-4 mt-4 rounded-md border border-emerald-100 bg-emerald-50 p-3">
          <p className="text-sm font-medium text-emerald-900">Created reminders</p>
          <div className="mt-2 space-y-2">
            {createdLinks.slice(0, 5).map((link) => (
              <div key={link.id} className="rounded-md bg-white/80 px-3 py-2 text-sm text-emerald-900">
                <div className="flex items-center justify-between gap-3">
                  <span className="min-w-0 truncate font-medium">{link.title}</span>
                  <span className={`shrink-0 rounded-full px-2 py-0.5 text-xs font-medium ${statusPillClass(link.status)}`}>
                    {link.status}
                  </span>
                </div>
                <div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-xs text-emerald-700">
                  <span>{link.listName ?? "Apple Reminders"}</span>
                  <span>Due {formatCompactDate(link.dueAt)}</span>
                  <span>Created {formatCompactDate(link.createdAt)}</span>
                </div>
              </div>
            ))}
          </div>
          {!isConnected(appleAccount) && (
            <p className="mt-2 text-xs text-emerald-700">Status refresh is unavailable until Apple Reminders is reconnected.</p>
          )}
        </div>
      )}

      {isGenerating && (
        <div className="mx-4 mt-4 flex items-center gap-2 rounded-md border border-emerald-100 bg-emerald-50 p-3 text-sm text-emerald-800">
          <Loader2 className="h-4 w-4 animate-spin" />
          Finding useful follow-up reminders...
        </div>
      )}

      {!isGenerating && drafts.length === 0 ? (
        <div className="p-6 text-center text-sm text-slate-500">
          No reminder suggestions are ready for this meeting.
        </div>
      ) : (
        <div className="divide-y divide-slate-100">
          {drafts.map((draft) => (
            <div key={draft.id} className="grid gap-4 p-4 lg:grid-cols-[minmax(0,1fr)_220px]">
              <div className="min-w-0 space-y-3">
                <label className="flex items-start gap-3">
                  <input
                    type="checkbox"
                    className="mt-1 h-4 w-4 rounded border-slate-300 text-emerald-600 focus:ring-emerald-600"
                    checked={draft.selected}
                    onChange={(event) => updateDraft(draft.id, { selected: event.target.checked })}
                  />
                  <input
                    className="min-w-0 flex-1 rounded-md border border-slate-300 px-3 py-2 text-sm font-medium text-slate-950 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100"
                    value={draft.title}
                    onChange={(event) => updateDraft(draft.id, { title: event.target.value })}
                    aria-label="Reminder title"
                  />
                </label>
                <textarea
                  className="min-h-20 w-full rounded-md border border-slate-300 px-3 py-2 text-sm text-slate-700 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100"
                  value={draft.notes ?? ""}
                  onChange={(event) => updateDraft(draft.id, { notes: event.target.value })}
                  aria-label="Reminder notes"
                />
                {draft.sourceEvidence.length > 0 && (
                  <div className="rounded-md border border-slate-200 bg-slate-50 p-3 text-sm text-slate-600">
                    <span className="font-medium text-slate-800">{draft.sourceEvidence[0].label}: </span>
                    {draft.sourceEvidence[0].snippet}
                  </div>
                )}
              </div>

              <div className="space-y-3">
                <div className="grid grid-cols-2 gap-2 lg:grid-cols-1">
                  <label className="text-xs font-medium text-slate-600">
                    Due
                    <input
                      type="datetime-local"
                      className="mt-1 w-full rounded-md border border-slate-300 px-2 py-2 text-sm text-slate-700 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100"
                      value={toDateTimeInput(draft.dueAt)}
                      onChange={(event) => updateDraft(draft.id, { dueAt: fromDateTimeInput(event.target.value) })}
                    />
                  </label>
                  <label className="text-xs font-medium text-slate-600">
                    Priority
                    <select
                      className="mt-1 w-full rounded-md border border-slate-300 px-2 py-2 text-sm text-slate-700 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100"
                      value={draft.priority ?? ""}
                      onChange={(event) => updateDraft(draft.id, { priority: event.target.value ? Number(event.target.value) : null })}
                    >
                      <option value="">None</option>
                      <option value="1">High</option>
                      <option value="5">Medium</option>
                      <option value="9">Low</option>
                    </select>
                  </label>
                </div>
                <label className="block text-xs font-medium text-slate-600">
                  List
                  <select
                    className="mt-1 w-full rounded-md border border-slate-300 px-2 py-2 text-sm text-slate-700 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100"
                    value={draft.listId ?? defaultList?.id ?? ""}
                    onChange={(event) => updateDraft(draft.id, { listId: event.target.value || null })}
                  >
                    {appleLists.length === 0 && <option value="">Default list</option>}
                    {appleLists.map((list: ReminderList) => (
                      <option key={list.id} value={list.id}>{list.name}</option>
                    ))}
                  </select>
                </label>
                <div className="flex flex-wrap gap-2 text-xs">
                  <span className="rounded-full bg-slate-100 px-2 py-1 font-medium text-slate-700">{categoryLabel(draft.category)}</span>
                  <span className="rounded-full bg-slate-100 px-2 py-1 text-slate-600">{priorityLabel(draft.priority)}</span>
                  {draft.confidence < 0.65 && (
                    <span className="rounded-full bg-amber-100 px-2 py-1 font-medium text-amber-800">Review</span>
                  )}
                </div>
                <div className="flex gap-2">
                  <button
                    type="button"
                    className="inline-flex flex-1 items-center justify-center gap-2 rounded-md bg-slate-900 px-3 py-2 text-sm font-medium text-white hover:bg-slate-800 disabled:opacity-50"
                    onClick={() => saveDraft(draft)}
                    disabled={!draft.dirty || savingDraftId !== null}
                  >
                    {savingDraftId === draft.id ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
                    Save
                  </button>
                  <button
                    type="button"
                    className="inline-flex items-center justify-center rounded-md border border-red-200 bg-white px-3 py-2 text-red-700 hover:bg-red-50 disabled:opacity-50"
                    onClick={() => dismissDraft(draft.id)}
                    disabled={savingDraftId !== null}
                    aria-label="Dismiss reminder suggestion"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
